export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const ADD_USER = "ADD_USER";
export const REMOVE_USER = "REMOVE_USER";
export const SET_USER_ID = "SET_USER_ID";

export const ADD_DRIVER_SUCCESS = "ADD_DRIVER_SUCCESS";
export const ADD_DRIVER_FAILED = "ADD_DRIVER_FAILED";
export const GET_USER_DRIVERS_SUCCESS = "GET_USER_DRIVERS_SUCCESS";
export const GET_USER_DRIVERS_FAILED = "GET_USER_DRIVERS_FAILED";
export const RESET_USER_DRIVERS_LIST = "GET_USER_DRIVERS_LIST";

export const ADD_DEVICE_SUCCESS = "ADD_DEVICE_SUCCESS";
export const ADD_DEVICE_FAILED = "ADD_DEVICE_FAILED";
export const GET_USER_DEVICES_SUCCESS = "GET_USER_DEVICES_SUCCESS";
export const GET_USER_DEVICES_FAILED = "GET_USER_DEVICES_FAILED";
export const RESET_USER_DEVICES_LIST = "GET_USER_DEVICES_LIST";

export const ADD_GEOFENCE_SUCCESS = "ADD_GEOFENCE_SUCCESS";
export const ADD_GEOFENCE_FAILED = "ADD_GEOFENCE_FAILED";
export const GET_USER_GEOFENCES_SUCCESS = "GET_USER_GEOFENCES_SUCCESS";
export const GET_USER_GEOFENCES_FAILED = "GET_USER_GEOFENCES_FAILED";
export const RESET_USER_GEOFENCES_LIST = "GET_USER_GEOFENCES_LIST";

export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";
export const ADD_GROUP_FAILED = "ADD_GROUP_FAILED";
export const GET_USER_GROUPS_SUCCESS = "GET_USER_GROUPS_SUCCESS";
export const GET_USER_GROUPS_FAILED = "GET_USER_GROUPS_FAILED";
export const RESET_USER_GROUPS_LIST = "GET_USER_GROUPS_LIST";

export const ADD_MAINTENANCE_SUCCESS = "ADD_MAINTENANCE_SUCCESS";
export const ADD_MAINTENANCE_FAILED = "ADD_MAINTENANCE_FAILED";
export const GET_USER_MAINTENANCES_SUCCESS = "GET_USER_MAINTENANCES_SUCCESS";
export const GET_USER_MAINTENANCES_FAILED = "GET_USER_MAINTENANCES_FAILED";
export const RESET_USER_MAINTENANCES_LIST = "GET_USER_MAINTENANCES_LIST";
