export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const RESET_CREDENTIALS = "RESET_CREDENTIALS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const SET_USER = "SET_USER";

export const GET_USER_DRIVERS_SUCCESS = "GET_USER_DRIVERS_SUCCESS";
export const RESET_USER_DRIVERS_LIST = "RESET_USER_DRIVERS_LIST";
export const SET_DRIVER = "SET_DRIVER";

export const GET_USER_DEVICES_SUCCESS = "GET_USER_DEVICES_SUCCESS";
export const SET_DEVICE = "SET_DEVICE";
export const RESET_USER_DEVICES_LIST = "GET_USER_DEVICES_LIST";
export const GET_DEVICE_TRIPS_SUCCESS = "GET_DEVICE_TRIPS_SUCCESS";
export const RESET_DEVICE_TRIPS = "RESET_DEVICE_TRIPS";

export const GET_USER_GEOFENCES_SUCCESS = "GET_USER_GEOFENCES_SUCCESS";
export const RESET_USER_GEOFENCES_LIST = "GET_USER_GEOFENCES_LIST";
export const SET_GEOFENCE = "SET_GEOFENCE";

export const GET_USER_GROUPS_SUCCESS = "GET_USER_GROUPS_SUCCESS";
export const RESET_USER_GROUPS_LIST = "GET_USER_GROUPS_LIST";

export const GET_USER_MAINTENANCES_SUCCESS = "GET_USER_MAINTENANCES_SUCCESS";
export const RESET_USER_MAINTENANCES_LIST = "GET_USER_MAINTENANCES_LIST";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

export const FETCH_TRIP_REPORT_SUCCESS = "FETCH_TRIP_REPORT_SUCCESS";
export const FETCH_SUMMARY_REPORT_SUCCESS = "FETCH_SUMMARY_REPORT_SUCCESS";
export const FETCH_STOP_REPORT_SUCCESS = "FETCH_STOP_REPORT_SUCCESS";
export const FETCH_EVENT_REPORT_SUCCESS = "FETCH_EVENT_REPORT_SUCCESS";
export const RESET_REPORTS = "RESET_REPORTS";
